import Head from 'next/head'
import MainComponent from '../components/main/Main'
import { GlobalStyle } from '../styles/Style'
import { ThemeProvider } from 'styled-components';
import { useSelector } from 'react-redux';
export default function Home() {
  const theme = useSelector((state) => state.theme.theme)
  return (
    <div >
      <Head>
        <title>Joshua Enrico</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet"></link>
      </Head>
      <ThemeProvider theme={theme}>
      <GlobalStyle />
      <MainComponent/>
      </ThemeProvider>

    </div>
  )
}
